### ISSUE TITLE
FrontEnd Button doesn't do anything for me

### ISSUE THREAD

**Issue by Rillithain** [lyrasoft/remoteimage#48]
hi, 
I have 2.0.5 installed, and I've given permissions to registered users to use RemoteImage front end; however, when they click the button nothing happens. Tried both IE and Chrome. It works on the back end. The user that is trying it on the front end is a superuser.  Using 3.4.1. Is there something I can check to resolve this?
Thanks, 
Rob

**Comment by asika32764** [comment]
Sorry for missing this issue, if there are new problem, feel free to open a new issue.
