### ISSUE TITLE
Unable to connect to backend.

### ISSUE THREAD

**Issue by tvovk** [lyrasoft/remoteimage#49]
Hi,
I am using RemoteImage 2.0.5 on Joomla 3.4.1 site. After the recent Joomla & RemoteImage update I started to receive random (so it looks) "Unable to connect to backend." errors. Sometimes it happen when i try to open a folder, sometimes when I try to rename or resize a file / image. I succeed If I try over and over again.. but it's very annoying.

Thanks and best regards,
Tomaž

**Comment by asika32764** [comment]
This will caused by many reasons, could you please open development tools, switch to Network tab and find what happened when ajax return?

**Comment by tvovk** [comment]
I forgot to mention that this happens in Firefox. There are two POST requests, response of the first one is always empty. See the images bellow. I tried to reproduce the problem in Chrome but everything works fine there. 
![remoteimage-post-1](https://cloud.githubusercontent.com/assets/813946/7166001/60928e40-e3ab-11e4-8d9c-e2efcd5fd796.png)
![remoteimage-post-2](https://cloud.githubusercontent.com/assets/813946/7166002/60bc537e-e3ab-11e4-82e5-6bbe026635ea.png)

**Comment by asika32764** [comment]
UTF-8 file name will break the ajax return value, I think maybe caused by this reason.

See: https://github.com/asikart/remoteimage/issues/52
