### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/remoteimage#50]
![p-2015-04-19-21](https://cloud.githubusercontent.com/assets/1639206/7217886/e96e287c-e67c-11e4-9bf2-c5d2eb8cf540.jpg)

**Comment by suhailaleryani** [comment]
hello i am having problem with the remoteimage it give me errors 
1) can not find the interface Jview  or can not implement it ==> i delete the /Jview from the file  and  it works  but i find some pb with style and view correctly 
2) Invalid backend response. Data is not JSON. how can i fix this problem , i looked every where i can not find anything to help  please help me

**Comment by asika32764** [comment]
Is this problem happened when you updating it?

**Comment by suhailaleryani** [comment]
it is the first time  , i just add it to my Joomla 3.3.3 Stable [ Ember ]

**Comment by asika32764** [comment]
UTF-8 file name will break the ajax return value, I think maybe caused by this reason.

See: https://github.com/asikart/remoteimage/issues/52
