### ISSUE TITLE
PNG files upload with black background instead of transparent

### ISSUE THREAD

**Issue by AlisaKirby** [lyrasoft/remoteimage#58]
I love this extension but am now noticing that any new PNGs I upload with transparent background upload with black background. Is anyone else having this issue?

**Comment by asika32764** [comment]
Try close `auto resize` in options.

**Comment by AlisaKirby** [comment]
That worked. Thank you.

**Comment by ravilongia** [comment]
I'm having the same problem. Can you tell me how to do this.

**Comment by AlisaKirby** [comment]
The suggestion above fixed the problem. See screen capture below. Set the "Auto Resize" option to "Disabled" and all will be fine.
![screenshot 2015-09-22 10 07 59](https://cloud.githubusercontent.com/assets/13969632/10020707/65081b68-6112-11e5-846c-a9f12d3239e8.png)
