### ISSUE TITLE
using this component for offloading data to image server

### ISSUE THREAD

**Issue by sandrodz** [lyrasoft/remoteimage#61]
Hi,

I've a high load website, I want to offload stress to several.

So I will have 5 apache servers with duplicate Joomla source code with load balancer. Now I don't want to carry around images to those 5 instances of site. I was thinking to create 6th server for images - it will have ftp/http access.

Joomla creates thumbs on pageload (when using uploading media for intro/featured image). Will J be able to save generated thumbs to image server via ftp?

**Comment by asika32764** [comment]
This is depends on elFinder not Joomla, so I think it is impossible now.

Sorry for missing this issue, if there are new problem, feel free to open a new issue.
