### ISSUE TITLE
Image Sort and Select after Upload

### ISSUE THREAD

**Issue by fmstatic59** [lyrasoft/remoteimage#62]
To be honest I hate the Joomla image Upload functionality. Your plugin/component was a huge relief..  so thank you so much for this great plugin.

When I am writing an article, the issue I face is that when I browse a photo from my computer, select it and click upload, it gets uploaded no issues but I have to look for the photo in the directory. Sometimes the uploaded photo get automatically selected to be inserted but sometimes it doesn't.  In either case how can the images can be sorted by date in the directory so the latest uploaded image comes up on top??

Thanks

**Comment by asika32764** [comment]
Unfortunately it is impossible now. Maybe this feature will implemented in next release.

Currently you can separate images into different folders to easily managed.

**Comment by asika32764** [comment]
Closed as elFinder is too old and Joomla built-in scripts do not support newer elFinder.

We'll consider implement similar features if we decided to create our own finder UI package.
