### ISSUE TITLE
Upgrade to 2.0.5 - No uploads anymore allowed

### ISSUE THREAD

**Issue by ppan2015** [lyrasoft/remoteimage#65]
Upgrade to 2.0.5
now I cannot upload any image file anymore, causing the error message "Upload Error. No file for upload found."

Working on Jooma 3.4.5.

**Comment by asika32764** [comment]
Hi, I can't reproduce this issue in a new Joomla 3.4.5 site with 2.0.5.

Please check there is no any conflict with other plugins.

(Maybe try reinstall ARI on a new site, or close some other plugins to test)

**Comment by asika32764** [comment]
Closed as no new comments.
