### ISSUE TITLE
PHP 7 Error: Cannot use 'String' as class name as it is reserved in [../String.php]

### ISSUE THREAD

**Issue by shkodskihk** [lyrasoft/remoteimage#67]
PHP Fatal error:  Cannot use 'String' as class name as it is reserved in //libraries/windwalker/vendor/joomla/string/src/String.php on line 19
[PHP 7; Joomla 3.4.8; RemoteImage 2.0.5]

**Comment by asika32764** [comment]
Please try 2.0.6
https://github.com/lyrasoft/remoteimage/releases/tag/2.0.6
