### ISSUE TITLE
Warning on Install. Windwalker 4.1.1 Not Activated

### ISSUE THREAD

**Issue by Bonitto** [lyrasoft/remoteimage#68]
Hi when I install latest version of Remote image I receive the following error. Remote Image also will not load.

Joomla version: 3.5
PHP 7

Warning

JInstaller: :Install: File does not exist /mnt/data/vhosts/casite-666661.cloudaccess.net/httpdocs/tmp/install_56f676f8539f0/remoteimage-staging/windwalker/resource
Library %s: Could not copy files from the source.

**Comment by asika32764** [comment]
I think it because Joomla 3.5 has some different on the installation process so ARI can not auto install Windwalker.

Try directly install Windwalker Framework
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1.1/windwalker-rad-2.1.1.zip

**Comment by Bonitto** [comment]
Hi,

Thanks for the quick reply.
Am I just copying and pasting the contents into the
root/libraries/windwalker or windwalker-bundle directory?

On Sat, Mar 26, 2016 at 10:33 AM, Simon Asika <notifications@github.com>
wrote:

> I think it because Joomla 3.5 has some different on the installation
> process so ARI can not auto install Windwalker.
>
> Try directly install Windwalker Framework
>
> https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1.1/windwalker-rad-2.1.1.zip
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lyrasoft/remoteimage/issues/68#issuecomment-201834180>
>



-- 
iCandy Webs, LLC Owner
Bonitto Daley, Jr.
Cell: 973-910-0130
Email: b.daley@icandywebs.com
Website: www.icandywebs.com

View our latest designs on Facebook: www.facebook.com/icandywebs and
Like the page to show your support. Thanks!

<http://www.facebook.com/icandywebs>

**Comment by asika32764** [comment]
You can install it from Joomla Extension Install page or copy to `libraries/windwalker`

**Comment by Bonitto** [comment]
Ok just fyi,

Using the default Joomla installer throws the following error:


On Sat, Mar 26, 2016 at 11:11 AM, Simon Asika <notifications@github.com>
wrote:

> You can install it from Joomla Extension Install page or copy to
> libraries/windwalker
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lyrasoft/remoteimage/issues/68#issuecomment-201853872>
>



-- 
iCandy Webs, LLC Owner
Bonitto Daley, Jr.
Cell: 973-910-0130
Email: b.daley@icandywebs.com
Website: www.icandywebs.com

View our latest designs on Facebook: www.facebook.com/icandywebs and
Like the page to show your support. Thanks!

<http://www.facebook.com/icandywebs>

**Comment by asika32764** [comment]
Did you checked the file permissions on your server? It seems Joomla can not operate your dirs.

I can successful install Windwalker on my Joomla 3.5 in PHP7

![p-2016-03-27-001](https://cloud.githubusercontent.com/assets/1639206/14061358/73883cb0-f3b9-11e5-9494-9343bdd73a3f.jpg)

![p-2016-03-27-002](https://cloud.githubusercontent.com/assets/1639206/14061359/738b10a2-f3b9-11e5-9daa-e62efcd7f2a8.jpg)

**Comment by Bonitto** [comment]
I'm sorry for the confusion I meant installing your windwalker zip could not install from the install manager.

**Comment by asika32764** [comment]
And the ARI also install successfully in a new empty Joomla 3.5

![p-2016-03-27-003](https://cloud.githubusercontent.com/assets/1639206/14061377/cf900cae-f3b9-11e5-947f-beab8aefb4cf.jpg)

**Comment by asika32764** [comment]
> I'm sorry for the confusion I meant installing your windwalker zip could not install from the install manager.

Do you mean the `install manager` is this page?

![p-2016-03-27-004](https://cloud.githubusercontent.com/assets/1639206/14061397/484d2c12-f3ba-11e5-92a3-fa8c66487f9e.jpg)

**Comment by Bonitto** [comment]
Yes sir

**Comment by asika32764** [comment]
I can install both ARI and windwalker normally.

Can you check your file permissions or the upload limit?

**Comment by Bonitto** [comment]
upload_max_filesize = 128M. Could I provide dev login creds to your email
for you to take a look perhaps to see if I have something misconfigured?

**Comment by asika32764** [comment]
OK, send the creds to asika32764 at gmail.com, I will check what happened.

**Comment by asika32764** [comment]
OK, after test, I can confirm there is some error on Linux server when installing, I need some time to fix this. Could you try just upload windwalker to `libraries/windwalker`?

If this still not work, then you must wait next version.

**Comment by asika32764** [comment]
Try 2.0.7
https://github.com/lyrasoft/remoteimage/releases/tag/2.0.7

**Comment by Bonitto** [comment]
That worked! Thanks so much again
