### ISSUE TITLE
Error after update the windwalker library

### ISSUE THREAD

**Issue by ribo72** [lyrasoft/remoteimage#70]
Hello after i updated the windwalker library i faced that error in backend and frontend when i try to open remoteimage
Warning: include_once(/libraries/windwalker/vendor/autoload.php): failed to open stream: No such file or directory in /libraries/windwalker/src/Windwalker.php on line 128

Warning: include_once(): Failed opening '/libraries/windwalker/vendor/autoload.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /libraries/windwalker/src/Windwalker.php on line 128

Warning: Class 'Windwalker\Router\CmsRoute' not found in /libraries/windwalker/src/Windwalker.php on line 139

Fatal error: Class 'Windwalker\DI\Container' not found in /libraries/windwalker/src/Windwalker.php on line 55

**Comment by ribo72** [comment]
Very strange. When you update windwalker library from joomla update component you see the error that i wrote before. After i installed the windwalker library from here https://github.com/ventoviro/windwalker-joomla-rad/releases version 2.1.5 and everything works fine, the errors gone

**Comment by asika32764** [comment]
Hi, sorry for inconvenience.

This issue caused by an earlier wrong package URL on the update server. I have fixed it.

The package you downloaded in release page is correct file. I think this issue can closed since the problem has been resolved.
