### ISSUE TITLE
issue with latest version 2.8.0

### ISSUE THREAD

**Issue by raramuridesign** [lyrasoft/remoteimage#71]
Hi Guys
the following error is showing when we update to the latest version
could you please urgently look into this.
Matthew

_Warning: include_once(/usr/www/users/XXXXXX/libraries/windwalker/vendor/autoload.php): failed to open stream: No such file or directory in /usr/www/users/XXXXXX/libraries/windwalker/src/Windwalker.php on line 128 Warning: include_once(): Failed opening '/usr/www/users/XXXXXX/libraries/windwalker/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /usr/www/users/XXXXXX/libraries/windwalker/src/Windwalker.php on line 128 Warning: Class 'Windwalker\Router\CmsRoute' not found in /usr/www/users/XXXXXX/libraries/windwalker/src/Windwalker.php on line 139 Fatal error: Class 'Windwalker\DI\Container' not found in /usr/www/users/XXXXXX/libraries/windwalker/src/Windwalker.php on line 55_

**Comment by asika32764** [comment]
It seems you miss Windawlker files in your site, try install Windwalker manually from Joomla installer
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1.5/windwalker-rad-2.1.5.zip

If you can't access admin, just upload it to `libraries/windwalker`, I thin it will work.

About this problem, I need more test to confirm this reason,

**Comment by raramuridesign** [comment]
Thanks, this is working ;-)
