### ISSUE TITLE
i Cant login after update to joomla 3.6.0

### ISSUE THREAD

**Issue by ribo72** [lyrasoft/remoteimage#72]
Hello, after update to joomla 3.6.0 when i try to login in frontend it shows blank page with error: Fatal error: Cannot redeclare RemoteimageBuildRoute() (previously declared in /components/com_remoteimage/router.php:30) in /components/com_remoteimage/router.php on line 30

**Comment by ribo72** [comment]
It happens because i have in login, menu item with remoteimage

**Comment by ribo72** [comment]
Is there any news about this bug?

**Comment by asika32764** [comment]
Please see https://github.com/lyrasoft/userxtd/issues/47 to do same action, add `if (function_exists('RemoteimageBuildRoute'))` to `RemoteimageBuildRoute()` and `RemoteimageParseRoute()`

I will release new version in a few days

**Comment by ribo72** [comment]
Hello, if i add 
if (function_exists('RemoteimageBuildRoute'))
}

and 
if (function_exists('RemoteimageParseRoute'))
}
but it s not work. May be i do something wrong

**Comment by asika32764** [comment]
Sorry, please add `!`.

``` php
if (!function_exists('RemoteimageBuildRoute'))

// ...
```

The `RemoteimageParseRoute()` too

**Comment by ribo72** [comment]
Hello, i add 

> !
but it still not work

**Comment by asika32764** [comment]
The error message still same as first?

**Comment by ribo72** [comment]
It shows blank page with Parse error: syntax error, unexpected end of file in /home/webdesig/public_html/artemis78.gr/components/com_remoteimage/router.php on line 78

**Comment by ribo72** [comment]
ok, i found it. i add also a } in line 78 and it works

**Comment by asika32764** [comment]
Please try 2.0.9
https://github.com/lyrasoft/remoteimage/releases/tag/2.0.9

**Comment by ribo72** [comment]
Thank you for the update. It works fine
