### ISSUE TITLE
Unable to connect to backend.

### ISSUE THREAD

**Issue by farhadst** [lyrasoft/remoteimage#74]
Hi simon
thanks for this great component
after update php version to 7.0.9 and remote image update to 2.0.9 get error
error is "Unable to connect to backend."
i have check error post #52 but not work for me
Thanks

**Comment by asika32764** [comment]
Have you try install Remoteimage in a pure new Joomla site?

**Comment by farhadst** [comment]
yes i have install remoteimage in a pure new joomla and everything's is ok
remoteimage work fast

**Comment by asika32764** [comment]
I think it maybe caused by some plugin conflicts.

**Comment by asika32764** [comment]
Closed since no future reaction. If anyone meet similar problem, please try the solution here: https://github.com/lyrasoft/remoteimage/issues/77#issuecomment-293232037
