### ISSUE TITLE
Repeated update

### ISSUE THREAD

**Issue by vru** [lyrasoft/remoteimage#75]
We're using Remote Image is some of our sites.
In one site I've got a update message indicating a new version of Remote Image was available (version 2.0.9).

I've updated the component from 2.0.8 to 2.0.9 without any errors, but when I return to the control panel the same message appears again indicating that I can update from 2.0.8 to 2.0.9.

I've cleared the chache and everything, but some how the updater indicates that the update has been installed, but when you check the extension manager, the version installed is 2.0.8, indicating the update didn't take place at all.

We've Joomla version 3.6.2 installed.

**Comment by asika32764** [comment]
Thank you for reporting this issue, I will check out that what caused this problem.

**Comment by pklinke** [comment]
I have same problem on all my sites. Only remove and reinstall helps. 

Peter

**Comment by vru** [comment]
I downloaded the latest version and installed that. That seems to work also.  So problem for me now is solved. Would be nice though to use the suggested update....
