### ISSUE TITLE
Joomla reports "Update 2.0.8->2.0.9 available"; update seems successful but Joomla still reports "update available"

### ISSUE THREAD

**Issue by christoph2806** [lyrasoft/remoteimage#76]
In the control panel, joomla reports "Update available" for asikart remote image (old 2.0.8, new 2.0.9). 
The update succeeds (no errors), but after the update, the components version is still 2.0.8. 
A fresh install of the extension from the extensions catalogue doesn't help, it stays at 2.0.8.
A fresh install of the extension from the package file (version 2.0.9) succeeds (so at least, this is a workaround).

System Information
Setting Value

PHP Built On    Linux Ubuntu-1304-raring-64-minimal-christoph2806 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64
Database Version    5.5.52-0ubuntu0.14.04.1
Database Collation  utf8_general_ci
Database Connection Collation   utf8mb4_general_ci
PHP Version 5.5.9-1ubuntu4.20
Web Server  Apache/2.4.7 (Ubuntu) SVN/1.8.8 PHP/5.5.9-1ubuntu4.20 OpenSSL/1.0.1f
WebServer to PHP Interface  apache2handler
Joomla! Version Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by asika32764** [comment]
It's seems the update server has a wrong version against the current version.

I released 2.0.10 to fix the update issue. Please try it.
https://github.com/lyrasoft/remoteimage/releases/tag/2.0.10

**Comment by christoph2806** [comment]
2.09. -> 2.0.10 works, thank you for your super fast reaction!
But I can't check whether it works from 2.0.8 too, because I upgraded to 2.0.9 via fresh install of 2.0.8; and 2.0.8 is  no longer available in the release section.

**Comment by asika32764** [comment]
Closed since it is resolved.
